=== OpenLightingProject/pid-schema/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "bitfield": {
      "type": "object",
      "properties": {
        "index": {
          "type": "integer",
          "minimum": 0
        },
        "name": {
          "$ref": "#/definitions/name"
        }
      },
      "required": ["index", "name"]
    },
    "command": {
      "type": "object",
      "properties": {
        "fields": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/field"
          }
        }
      },
      "required": ["fields"]
    },
    "field": {
      "type": "object",
      "oneOf": [
        {
          "properties": {
            "type": {
              "enum": ["bitfield"]
            },
            "bits": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/bitfield"
              }
            },
            "size": {
              "type": "integer",
              "multipleOf": 8
            }
          },
          "required": ["bits", "type", "size"]
        },
        {
          "properties": {
            "type": {
              "enum": ["bool"]
            },
            "name": {
              "$ref": "#/definitions/name"
            }
          },
          "required": ["name", "type"]
        },
        {
          "properties": {
            "type": {
              "enum": ["int8", "int16", "int32", "int64",
                       "uint8", "uint16", "uint32", "uint64"]
            },
            "name": {
              "$ref": "#/definitions/name"
            },
            "labels": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/label"
              }
            },
            "prefix": {
              "type": "integer",
              "maximum": 255,
              "minimum": 0
            },
            "ranges": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/range"
              }
            },
            "unit": {
              "type": "integer",
              "maximum": 255,
              "minimum": 0
            }
          },
          "required": ["name", "type"]
        },
        {
          "properties": {
            "type": {
              "enum": ["string"]
            },
            "name": {
              "$ref": "#/definitions/name"
            },
            "max_size": {
              "type": "integer",
              "minimum": 0,
              "exclusiveMinimum": true
            },
            "min_size": {
              "type": "integer",
              "minimum": 0
            }
          },
          "required": ["name", "type"]
        },
        {
          "properties": {
            "type": {
              "enum": ["ipv4"]
            },
            "name": {
              "$ref": "#/definitions/name"
            }
          },
          "required": ["name", "type"]
        },
        {
          "properties": {
            "type": {
              "enum": ["mac"]
            },
            "name": {
              "$ref": "#/definitions/name"
            }
          },
          "required": ["name", "type"]
        },
        {
          "properties": {
            "type": {
              "enum": ["uid"]
            },
            "name": {
              "$ref": "#/definitions/name"
            }
          },
          "required": ["name", "type"]
        },
        {
          "properties": {
            "type": {
              "enum": ["group"]
            },
            "name": {
              "$ref": "#/definitions/name"
            },
            "fields": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/field"
              }
            },
            "max_size": {
              "type": "integer",
              "minimum": 0,
              "exclusiveMinimum": true
            },
            "min_size": {
              "type": "integer",
              "minimum": 0
            }
          },
          "required": ["name", "fields", "type"]
        }
      ]
    },
    "label": {
      "type": "object",
      "properties": {
        "label": {
          "minLength": 1,
          "type": "string"
        },
        "value": {
          "type": "integer",
          "maximum": 4294967295,
          "minimum": 0
        }
      },
      "required": ["label", "value"]
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "range": {
      "type": "object",
      "properties": {
        "lower": {
          "type": "integer"
        },
        "upper": {
          "type": "integer"
        }
      },
      "required": ["lower", "upper"]
    }
  },
  "type": "object",
  "properties": {
    "get_request": {
      "$ref": "#/definitions/command"
    },
    "get_response": {
      "$ref": "#/definitions/command"
    },
    "get_subdevice_range": {
      "maximum": 3,
      "minimum": 0,
      "type": "integer"
    },
    "name": {
      "minLength": 1,
      "type": "string"
    },
    "pid": {
      "maximum": 65535,
      "minimum": 0,
      "type": "integer"
    },
    "set_request": {
      "$ref": "#/definitions/command"
    },
    "set_response": {
      "$ref": "#/definitions/command"
    },
    "set_subdevice_range": {
      "maximum": 3,
      "minimum": 0,
      "type": "integer"
    },
    "version": {
      "minimum": 0,
      "type": "integer"
    }
  },
  "required": ["name", "pid", "version"],
  "dependencies": {
    "get_request": ["get_response", "get_subdevice_range"],
    "get_response": ["get_request", "get_subdevice_range"],
    "get_subdevice_range": ["get_request", "get_response"],
    "set_request": ["set_response", "set_subdevice_range"],
    "set_response": ["set_request", "set_subdevice_range"],
    "set_subdevice_range": ["set_request", "set_response"]
  }
}

=== OpenLightingProject/pid-schema/data/device_info.json
{
  "name": "DEVICE_INFO",
  "pid": 96,
  "version": 1,
  "get_request": {
    "fields": []
  },
  "get_response": {
    "fields": [
      {"name": "protocol_major", "type": "uint8"},
      {"name": "protocol_minor", "type": "uint8"},
      {"name": "device_model", "type": "uint16"},
      {"name": "product_category", "type": "uint16"},
      {"name": "software_version", "type": "uint32"},
      {
        "name": "dmx_footprint",
        "type": "uint16",
        "ranges": [
          {
            "lower": 0,
            "upper": 512
          }
        ],
        "labels": [
          {
            "label": "No footprint",
            "value": 65535
          }
        ]
      },
      {"name": "current_personality", "type": "uint8"},
      {"name": "personality_count", "type": "uint8"},
      {"name": "dmx_start_address", "type": "uint16"},
      {"name": "sub_device_count", "type": "uint16"},
      {"name": "sensor_count", "type": "uint8"}
    ]
  },
  "get_subdevice_range": 2
}

=== OpenLightingProject/pid-schema/data/proxied_devices.json
{
  "name": "PROXIED_DEVICES",
  "pid": 16,
  "version": 1,
  "get_request": {
    "fields": []
  },
  "get_response": {
    "fields": [
      {
        "name": "devices",
        "type": "group",
        "fields": [
          {
            "name": "uid",
            "type": "uid"
          }
        ]
      }
    ]
  },
  "get_subdevice_range": 2
}

=== OpenLightingProject/pid-schema/data/dmx_start_address.json
{
  "name": "DMX_START_ADDRESS",
  "pid": 240,
  "version": 1,
  "get_request": {
    "fields": []
  },
  "get_response": {
    "fields": [
      {
        "name": "start_address",
        "type": "uint16",
        "ranges": [
          {
            "lower": 0,
            "upper": 512
          }
        ],
        "labels": [
          {
            "label": "No footprint",
            "value": 65535
          }
        ]
      }
    ]
  },
  "get_subdevice_range": 2,
  "set_request": {
    "fields": [
      {
        "name": "start_address",
        "type": "uint16",
        "ranges": [
          {
            "lower": 0,
            "upper": 512
          }
        ],
        "labels": [
          {
            "label": "No footprint",
            "value": 65535
          }
        ]
      }
    ]
  },
  "set_response": {
    "fields": []
  },
  "set_subdevice_range": 3
}

=== OpenLightingProject/pid-schema/data/bitfields.json
{
  "name": "PROXIED_DEVICES",
  "pid": 16,
  "version": 1,
  "get_request": {
    "fields": []
  },
  "get_response": {
    "fields": [
      {
        "type": "bitfield",
        "size": 8,
        "bits": [
          {
            "index": 0,
            "name": "foo"
          }
        ]
      }
    ]
  },
  "get_subdevice_range": 0
}
